/* eslint-disable @typescript-eslint/no-var-requires */


const esbuild = require("esbuild");
const builtins = require('builtin-modules')
const postCssPlugin = require("esbuild-style-plugin");


const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const outDir = "vault/.obsidian/plugins/obsidian-graph-presets/"
esbuild
	.build({
		plugins: [
			postCssPlugin({
				postcss: {
					plugins: [require("tailwindcss"), require("autoprefixer")],
				},
			}),
		],
		banner: {
			js: banner,
		},
		
		entryPoints: ["src/main.ts","src/styles.css"],
		bundle: true,
		jsx: "automatic",
		external: [
			"obsidian",
			"electron",
			"@codemirror/autocomplete",
			"@codemirror/collab",
			"@codemirror/commands",
			"@codemirror/language",
			"@codemirror/lint",
			"@codemirror/search",
			"@codemirror/state",
			"@codemirror/view",
			"@lezer/common",
			"@lezer/highlight",
			"@lezer/lr",
			...builtins,
		],
		format: "cjs",
		watch: !prod,
		target: "es2018",
		logLevel: "info",
		sourcemap: prod ? false : "inline",
		treeShaking: true,
		outdir:outDir,
	})
	.catch(() => process.exit(1));
